### ISSUE TITLE
[Packaging] sn0int

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#25]
Facilitate packaging for sn0int https://github.com/kpcyrd/sn0int and modify build script when completed.

@kpcyrd FYI

**Comment by xFreed0m** [comment]
Done - not by me, but seems to work:
![image](https://user-images.githubusercontent.com/13978578/96264374-c81cae80-0fcc-11eb-8b9a-93e11f1493c3.png)

**Comment by kpcyrd** [comment]
@xFreed0m as far as I know this ticket was about packaging for kali linux (unfortunately with no progress yet since I started taking a break from open source and the debian-rust situation is complicated), the sn0int binary is currently provided like this: https://github.com/tracelabs/tlosint-live/blob/b2fba6fb4c95d24f0c328b63120d6bfcc4c49008/kali-config/common/hooks/normal/osint-packages.chroot#L85-L90

Note that this can be simplified to:
```
cargo install sn0int
mv /root/.cargo/bin/sn0int /usr/bin
```
This allows you to drop the wrapper script in `kali-config/common/includes.chroot/usr/bin/sn0int`.

**Comment by xFreed0m** [comment]
oh, i thought this ticket was for getting sn0int into the tlosint VM. you want me to reopen it?
you can also open a bug in kali linux for incorporating your tool and get their help with it.

**Comment by phunkpwnz** [comment]
Yea the ticket was for packaging for Kali. Currently it looks like the dependencies aren't met in the current Kali setup. Reopening this in the meantime.

**Comment by 5nacks** [comment]
Closing this of as it is an aged ticket.
